### ISSUE TITLE
Transcribe exchange whitepaper PDF

### ISSUE THREAD

**Issue by cbeams** [bisq-network/docs#2]
- [x] Transcribe https://bisq.network/docs/bitsquare.pdf to Asciidoc
- [x] s/Bitsquare/Bisq/g
- ~~Fix obvious inaccuracies, e.g. trading fees~~
- [x] Set up netlify redirect in bisq-network/website from old pdf => new adoc
- [x] Remove bitsquare.pdf from bisq-network/website

**Comment by cbeams** [comment]
@ManfredKarrer, where is the source (i.e. GDoc) for v1.2 of the exchange whitepaper at https://bisq.network/docs/bitsquare.pdf? I cannot find it in Google Drive—only older versions like 0.9 and 1.0.

**Comment by cbeams** [comment]
Closing as complete. The exchange whitepaper PDF has been transcribed to https://github.com/bisq-network/docs/blob/master/exchange/whitepaper.adoc and will be managed there from this point on. Redirects are in place for old PDF urls, etc.

The doc has only been transcribed. It still needs to be edited for accuracy. That will be managed in a separate issue.

/cc @ManfredKarrer

**Comment by ManfredKarrer** [comment]
@cbeams The file was here: https://docs.google.com/document/d/1piHqGwFTVBhV6QID8Mkq0c5Vc5nF4TO-gGlU33oABdA/edit#heading=h.5sj0n072pltm
I added you for access
