### ISSUE TITLE
Github Not Fully Highlighting Diff

### ISSUE THREAD

**Issue by Francewhoa** [bisq-network/docs#23]
### Steps to reproduce

1. Using the github interface, fork this repository https://github.com/bisq-network/docs
1. Also fork this parent repository https://github.com/bisq-network
1. Using the first fork above `/bisq-network/docs`, edit this `phase-zero.adoc` file
      1. Under "Introduction" section, remove 3 characters, any
1. Still using github interface, send a pull request
      1. During your pull request, on the “Comparing changes” page, notice that the diff is not fully highlighted. This is the challenge. Find screenshot below to clarify the location of this challenge. It's the first time I saw that "glitch" with github. 
1. The expected result is that the diff is fully highlighted like in [this test](https://user-images.githubusercontent.com/119942/34324135-208a109e-e81b-11e7-8126-48242f46b0db.jpg) with another file. The fully highlighted diff allows to quickly and easily tell what is the suggested edit and its exact location. That's the whole point of a diff, LOL ;) Otherwise it's time consuming to read the whole paragraph and manually try to locate the edit.
1. I was able to reproduce this challenge only when using this forked `phase-zero.adoc` file. I was _not_ able to reproduce this challenge with any [other files](https://github.com/Francewhoa/docs/tree/master/dao) within the same forked repository.

### Screenshot challenge

![screenshot challenge---wn](https://user-images.githubusercontent.com/119942/34324262-0c446020-e821-11e7-8308-535bd26f6ea2.jpg)

### Notes

* Related https://github.com/bisq-network/docs/pull/22#issuecomment-353719447
* Related tweet by cbeams at https://twitter.com/cbeams/status/944162513482145792

**Comment by Francewhoa** [comment]
Today I reported this challenge to github. Waiting their reply. I'll post it here if any.

**Comment by Francewhoa** [comment]
Reply from Rachel, GitHub staff

> Hey Francois,
> 
>>   Steps to reproduce at https://github.com/bisq-network/docs/issues/23#issue-284342546
> 
> Thanks for writing in! It looks like you've run up against a limitation we put in place to keep our site performance up. We currently stop running word diffs on single lines that go past 512 characters, and that line seems to be over that. I'll definitely add your +1 for bumping that limit up though! Let me know if there's anything else I can help with in the meantime.
> 
> All the best,
> Rachel
> GitHub Support

**Comment by cbeams** [comment]
Thanks @francewhoa, for solving the mystery!

Really hope GitHub does increase that 512 char limit, because that is effectively limiting writers to 512 char paragraphs—for those who subscribe to the one-line-per-paragraph approach as we do.

**Comment by Francewhoa** [comment]
@cbeams :) Yeah that limit is a party crasher for doc contributors. It also makes it harder for maintainers to review for approval pull request :( As you know documentation paragraphs often need to go over that limit. Simply because they are text visible to end-users, not line of codes, or in-line code comments visible to back-end software engineers. Also doc contributors need that full length for easy and quick automated doc spell checks, frequents updates. Plus a pleasant end-user experience when they read the doc on devices with different screen sizes with automated line brakes.

Until that limit is removed, for my future pull requests, I'm happy to try to use the pull request comment field to try to manually clarify what the propose pull request is about. I mean using this pull request as an example, **which one of the following two options is easier for you when you review future pull requests?**

## Option 1: Diff location

```
There is a minor typo with the "to" word. The propose update is located into this sentence:

"This document is written to provide a clear..."
```


## Option 2: Manual diff 

```
There is a minor typo with the "to" word. I propose this:

Before
"This document is written to to provide a clear..."

After
"This document is written to provide a clear..."
```

## Option 3: What else?

Do you have any other proposal to resolve this limit party-crasher challenge?


Option 1 is easier for me. How about u? Option 2 might be challenging if there are multiple propose edits within the same sentence.
