### ISSUE TITLE
Add 3 Doc Teams?

### ISSUE THREAD

**Issue by Francewhoa** [bisq-network/docs#24]
Hi @cbeams, @ManfredKarrer, and all Bisq enthusiasts :)

Happy Christmas if you're celebrating that

This whole ticket is a proposal. About this Bisq "Teams" page at https://github.com/orgs/bisq-network/teams
To facilitate communications between people interested to contribute to the Bisq documentation, how about adding the following 3 new teams?

## Teams

Proposed team names

1. **`doc-admins`**
1. **`doc-maintainers`** 
1. **`doc-contributors`**

## Usage

Proposed usage

1. **`doc-admins`** 
Member(s) of this team are interested in administrative tasks related to Bisq documentation. For example member(s) would have access to add or remove members to the **`doc-admins`**, **`doc-maintainers`**, **`doc-contributors`** teams, and doc repo(s).
1. **`doc-maintainers`** 
Member(s) of this team are interested in tasks such as reviewing for approval Bisq doc contributions. For example review for approval the pull requests related to the doc repo(s). I'm assuming that for now only @cbeams needs this? In the future, and when needed members of the `docs-admins` team could add additional members? Depending on their present admin(s) workload.
1. **`doc-contributors`**
Member(s) of this team are interested in tasks such as contributing to Bisq docs. For example maintaining the already existing docs. So that they remain fresh and useful. For example if the Bisq software has a new feature or a existing workflow as changed, then update it accordingly. Or contributing new docs.

Of course all of the above 3 teams would be useful for notification, for example `@doc-contributors` could be use to [notify](https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams) volunteers asking for their availability & interest to update or create a doc text, screenshots, links, video, etc.

## Location

How about adding those 3 teams [nested](https://help.github.com/articles/about-teams/#nested-teams) under this "[contributors](https://github.com/orgs/bisq-network/teams/contributors)" team?

As for the permissions, how about those 3 new teams would be [visible](https://help.github.com/articles/about-teams/#team-visibility)? I don't see any security risk with this.

## Notes

@Francewhoa :) Notes to myself. Docs related to github teams:
* About https://help.github.com/articles/about-teams/
* Notification https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams
* Repo permissions https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by cbeams** [comment]
Something like this could make sense once we have a number of people actively contributing to docs. For now, it's enough to just have @bisq-network/docs-maintainers + people doing individual pull requests (like yourself @Francewhoa). But the thinking is good. Let's grow the contributor base to the point where we need this, eh?

**Comment by cbeams** [comment]
Note that I realized that I hadn't actually created @bis-network/docs-maintainers prior to this issue, which I had meant to do. I've added that now.

**Comment by Francewhoa** [comment]
@cbeams :) Thanks for your reply. How many active contributors to the docs presently? 

I'm asking because this proposal is based on my guess-timate that they are presently 3 to 6 active contributors to Bisq docs? Between 3-6 interested contributors, those 3 teams would be useful to some now. But if there is presently only 1-2 active contributors, I agree it's too early to start the Github teams party, LOL ;) Maybe I missed the target on my guess-timate? 

To clarify this proposal, today I reformatted it using the User Story and Assumptions format

> ## User Story
> 
> As contributors to Bisq documentation (docs) we need 3 Github teams so that:
> * the on-boarding of newcomers docs contributors is facilitated
> * communications, and notifications/mentions are easier and faster
> * the risk of some contributors being left out of the communication loops is reduced
> * the noise in the communications is reduce
> * the newcomers contributors have a pleasant initial experience. Which in turn increase the retention. Which in turn increase the amount of docs contributors.
> 
> ## Assumptions
> 
> * Assumes this proposal is only for docs contributors interested in both using Github and using Github teams. Because some contributors may not be interested in those tools. In other words, the intention of this proposal is not about interfering with other volunteer contributors, or forcing tools or workflows on them. To each their own how, when, where they contribute. The only intent of this proposal is stated in the User Story above.
> * Assumes those proposed team names
>       1. **`docs-admins`**
>       1. **`docs-maintainers`** 
>       1. **`docs-contributors`**
> * Assumes those proposed usage
>       1. **`doc-admins`** 
>             Member(s) of this team are interested in administrative tasks related to Bisq documentation. For example member(s) would have access to add or remove members to the **`doc-admins`**, **`doc-maintainers`**, **`doc-contributors`** teams, and doc repo(s).
>       1. **`doc-maintainers`** 
>             Member(s) of this team are interested in tasks such as reviewing for approval Bisq doc contributions. For example review for approval the pull requests related to the doc repo(s). I'm assuming that for now only @cbeams needs this? In the future, and when needed members of the `docs-admins` team could add additional members? Depending on their present admin(s) workload.
>       1. **`doc-contributors`**
>             Member(s) of this team are interested in tasks such as contributing to Bisq docs. For example maintaining the already existing docs. So that they remain fresh and useful. For example if the Bisq software has a new feature or a existing workflow as changed, then update it accordingly. Or contributing new docs.
> * Assumes the 3 Github teams would be useful for notification, for example `@doc-contributors` could be use to [notify](https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams) volunteers asking for their availability & interest to update or create a doc text, screenshots, links, video, etc.
> * Assumes the new Github teams are [nested](https://help.github.com/articles/about-teams/#nested-teams) under this "[contributors](https://github.com/orgs/bisq-network/teams/contributors)" team
> * Assumes the new Github teams permissions are [visible](https://help.github.com/articles/about-teams/#team-visibility)

 
As you know this is a proposal, suggestion to adapt it are always welcome :) If you're not interested feel really free to decline :)

**Comment by cbeams** [comment]
@Francewhoa, the only people working on docs at the moment are you and me :)

This is why I'm saying that, while I generally like the thinking above, doing more stuff with teams can wait until there are actually teams of people doing stuff :)

Thanks though, much appreciated.

**Comment by Francewhoa** [comment]
@cbeams :) Well two people is twice as much as none. And better than nothing, LOL ;)
