### ISSUE TITLE
Request for refund of holding deposit

### ISSUE THREAD

**Issue by so11github** [bisq-network/docs#25]
Hi,

1. Attempted to accept a trade for bitcoins Dec 22. Transaction id:
Transaction  b50b2834adab6a2cd01df49291751ee0664d5d00002ef3e300e68f15f2f87efa

2. Holding deposit was withheld:
18GzH11T5h2fpvUoBJDub7MgNJVw3FfqQ8 | 0.00020000 |  
-- | -- | --

3. The trade failed due to a time-out error. Error message:"A timeout occurred".
Selected arbitrator: 3b7cft5k4ae6a236.onion:9999

Could you please let me know when to expect the holding deposit to be returned to my account?

Many thanks

**Comment by cbeams** [comment]
Just noticed this issue, which is in the wrong repository. If this matter has not yet been resolved, please open an issue at https://github.com/bisq-network/support, thanks.
